<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:

The input layer of a neural network or a simple perceptron consist of a passive input which conveys information conveyed to them into the web of the hidden or output layers of the system.

### Hidden Layer:



### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [152]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }
inputs = pd.DataFrame.from_dict(data)

df = pd.DataFrame.from_dict(data).astype('int')

In [153]:
type(inputs)

inputs_parse = np.array([
    [inputs['x1'][0], inputs['x2'][0]],
    [inputs['x1'][1], inputs['x2'][1]],
    [inputs['x1'][2], inputs['x2'][2]],
    [inputs['x1'][3], inputs['x2'][3]],
])

In [154]:
inputs_parse.shape

(4, 2)

In [155]:
X = pd.DataFrame(inputs_parse)

In [156]:
type(X)

pandas.core.frame.DataFrame

In [157]:
type(inputs_parse)

numpy.ndarray

In [158]:
inputs_parse

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [159]:
y = inputs['y']


In [160]:
y

0    1
1    1
2    1
3    0
Name: y, dtype: int64

In [161]:
type(y)

pandas.core.series.Series

In [162]:
len(y)

4

In [163]:
y = np.array(y)

In [164]:
y = y.reshape((-1,1))

In [165]:
y

array([[1],
       [1],
       [1],
       [0]])

In [166]:
type(y)

numpy.ndarray

In [167]:
np.random.seed(1966)

In [168]:
##### Your Code Here #####
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

weights = 2 * np.random.random((2,1)) - 1


for iteration in range(10):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs_parse, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = y - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs_parse.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 0.12363589]
 [-0.1605986 ]]
Output after training
[[0.5       ]
 [0.5323067 ]
 [0.45681395]
 [0.48905959]]


In [148]:
weights

array([[ 0.35385815],
       [ 0.17552995],
       [ 0.55152509],
       [-0.85156943]])

In [149]:
inputs_parse

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [82]:
import numpy as np #turning lists into arrays
import seaborn as sns #data loader
import pandas as pd #manipulate data
import category_encoders as ce #encoding
from sklearn.model_selection import train_test_split # data splitting
from sklearn.preprocessing import MinMaxScaler # normalization
from sklearn.impute import SimpleImputer # fill NaN values
from sklearn.pipeline import make_pipeline # creating a pipeline
from sklearn.metrics import accuracy_score #scoring metric

In [110]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [111]:
diabetes.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [112]:
diabetes.shape

(768, 9)

In [113]:
768-768/10

691.2

In [114]:
691*.2

138.20000000000002

In [115]:
768 - 69 - 138

561

In [116]:
561 + 69 + 138

768

In [117]:
pipe = make_pipeline(
    ce.OrdinalEncoder(), #encode categoricals
    SimpleImputer(strategy="median"), #fill the NaN's
    MinMaxScaler() # change values to be represented between 0 and 1
)

In [118]:
target = 'Outcome'

In [119]:
X = diabetes.drop(target, axis=1)

In [120]:
y = diabetes[target]

In [121]:
X_train = X.loc['1':'561']

In [122]:
X_val = X.loc['561':'698']

In [123]:
y_test = y.loc['699':'768']

In [124]:
print(X_train.shape)
print(X_val.shape)
print(y_test.shape)

(561, 8)
(138, 8)
(69,)


In [125]:
# apply pipe
X_train = pipe.fit_transform(X_train)
print(f"""X_train Shape: {X_train.shape}
""")

X_train Shape: (561, 8)



In [126]:
# apply pipe
X_val = pipe.fit_transform(X_val)
print(f"""X_val Shape: {X_val.shape}
""")

X_val Shape: (138, 8)



In [127]:
X_val

array([[0.        , 0.99300699, 0.57894737, ..., 0.72076789, 0.25836431,
        0.14285714],
       [0.07692308, 0.21678322, 0.59649123, ..., 0.65619546, 0.19578686,
        0.06122449],
       [0.46153846, 0.3006993 , 0.52631579, ..., 0.46945899, 0.25526642,
        0.2244898 ],
       ...,
       [0.23076923, 0.79020979, 0.64912281, ..., 0.52181501, 0.1133829 ,
        0.20408163],
       [0.        , 0.3006993 , 0.        , ..., 0.43630017, 0.10408922,
        0.02040816],
       [0.30769231, 0.4965035 , 0.77192982, ..., 0.60209424, 0.31784387,
        0.14285714]])

In [128]:
X_train

array([[0.05882353, 0.42929293, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.92424242, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       [0.05882353, 0.44949495, 0.54098361, ..., 0.41877794, 0.03800171,
        0.        ],
       ...,
       [0.64705882, 0.42929293, 0.60655738, ..., 0.4485842 , 0.09479078,
        0.23333333],
       [0.35294118, 0.63131313, 0.62295082, ..., 0.50372578, 0.01836038,
        0.55      ],
       [0.        , 1.        , 0.54098361, ..., 0.61549925, 0.18104184,
        0.11666667]])

In [130]:
y_test

699    0
700    0
701    1
702    1
703    0
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 69, dtype: int64

In [131]:
y = np.array(y)

In [133]:
y = y.reshape((-1,1))
y.shape

(768, 1)

In [135]:
y_test = np.array(y_test)

In [136]:
y_test = y_test.reshape((-1,1))

In [137]:
y_test

array([[0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

###### Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [10]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [142]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
#    def __sigmoid_derivative(self, x):
#        return None

#    def fit(self, X, y):
#    """Fit training data
#    X : Training vectors, X.shape : [#samples, #features]
#    y : Target values, y.shape : [#samples]
#    """

for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(X_train, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = y - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(X.T, adjustments)    
    
    
        # Randomly Initialize Weights
#        weights = ...

#        for i in range(self.niter):
            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

            # Update the Weights


#    def predict(self, X):
#    """Return class label after unit step"""
#        return None

ValueError: shapes (561,8) and (4,1) not aligned: 8 (dim 1) != 4 (dim 0)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?